--CREATE DATABASE Stocks;
--USE Stocks;

DROP TABLE COMPANIES;
CREATE TABLE COMPANIES(
	STOCK_SYMBOL VARCHAR(5) NOT NULL PRIMARY KEY, 
	COMPANY_NAME VARCHAR(60),
	INDUSTRY_1 VARCHAR(60),
	INDUSTRY_2 VARCHAR(60),
	CITY VARCHAR(60),
	STATE CHAR(2),
	ACTIVE_IND CHAR(1)
);

DROP TABLE FINANCIALS;
CREATE TABLE FINANCIALS(
	FINANCIALS_ID INT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY, --Auto-increments the primary key
	STOCK_SYMBOL VARCHAR(5),
	FISCAL_YEAR INT,
	REVENUE NUMERIC(12,2),
	PROFIT NUMERIC(12,2),
	OPERATING_INCOME NUMERIC(12,2),
	NET_INCOME NUMERIC(12,2),
	ASSETS NUMERIC(12,2),
	EQUITY NUMERIC(12,2)
);

ALTER TABLE FINANCIALS
	FOREIGN KEY (STOCK_SYMBOL) REFERENCES COMPANIES(STOCK_SYMBOL);

DROP TABLE STOCK_PRICE;
CREATE TABLE STOCK_PRICE(
	STOCK_PRICE_ID INT NOT NULL PRIMARY KEY,
	STOCK_SYMBOL VARCHAR(5),
	STOCK_DATE DATE,
	STOCK_OPEN NUMERIC(10,2),
	STOCK_CLOSE NUMERIC(10,2),
	STOCK_LOW NUMERIC(10,2),
	STOCK_HIGH NUMERIC(10,2),
	STOCK_VOLUME INT,
	STOCK_DIVIDENDS NUMERIC(5,2)
);

ALTER TABLE STOCK_PRICE
	FOREIGN KEY (STOCK_SYMBOL) REFERENCES COMPANIES(STOCK_SYMBOL);

--Sets the first ID to 1 after intial historical data upload (csv upload starts at 0)
UPDATE STOCK_PRICE 
SET STOCK_PRICE_ID = STOCK_PRICE_ID + 1;

--Sets only companies with profit data to active. This is to limit the number of API requests in the Airflow pipeline
UPDATE COMPANIES
	SET ACTIVE_IND = 'Y' WHERE STOCK_SYMBOL
	IN(SELECT STOCK_SYMBOL FROM FINANCIALS WHERE PROFIT <> 0)

	
